/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Modelo.Conexion;
import Modelo.ConsultasSql;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farro
 */
public class GestionarPersonal extends javax.swing.JFrame {

    /**
     * Creates new form AgregarUsuario
     */
    public GestionarPersonal() {
        initComponents();
        cargarProfesiones(jCombProfesion);
        cargarCondiciones(jCombCondicion);
        cargarTablaPersonal(jTablePersonal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        jCombGenero = new javax.swing.JComboBox<>();
        jCombCondicion = new javax.swing.JComboBox<>();
        jCombProfesion = new javax.swing.JComboBox<>();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        bttAgregar = new javax.swing.JButton();
        bttEliminar = new javax.swing.JButton();
        bttModificar = new javax.swing.JButton();
        bttLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 610, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Gestion de Personal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 190, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido Paterno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido Materno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha Nacimiento:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Condición:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Profesión:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, -1));
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 130, -1));

        jCombGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(jCombGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 90, -1));

        jPanel1.add(jCombCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 170, -1));

        jPanel1.add(jCombProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 170, -1));
        jPanel1.add(jDateFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 130, -1));

        bttAgregar.setText("Agregar");
        bttAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(bttAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 90, -1));

        bttEliminar.setText("Eliminar");
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bttEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 90, -1));

        bttModificar.setText("Modificar");
        bttModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificarActionPerformed(evt);
            }
        });
        jPanel1.add(bttModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 90, -1));

        bttLimpiar.setText("Limpiar");
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarActionPerformed
        String dni = txtDni.getText().trim();
        String nombres = txtNombres.getText().trim();
        String apellidoP = txtApellidoP.getText().trim();
        String apellidoM = txtApellidoM.getText().trim();

        java.util.Date utilDate = jDateFechaNacimiento.getDate();
        java.sql.Date sqlDate = null;

        if (utilDate != null) {
            sqlDate = new java.sql.Date(utilDate.getTime());
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha de nacimiento");
            return;
        }

        String genero = "";
        if (jCombGenero.getSelectedItem() != null) {
            genero = jCombGenero.getSelectedItem().toString();
            if (!genero.equals("M") && !genero.equals("F")) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un género válido (M o F)");
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un género");
            return;
        }

        String profesionDesc = jCombProfesion.getSelectedItem().toString();
        String condicionDesc = jCombCondicion.getSelectedItem().toString();

        int idProfesion = ConsultasSql.obtenerIdProfesion(profesionDesc);
        int idCondicion = ConsultasSql.obtenerIdCondicion(condicionDesc);

        if (idProfesion == -1 || idCondicion == -1) {
            JOptionPane.showMessageDialog(null, "Error al obtener profesión o condición.");
            return;
        }

        String sqlInsert = "INSERT INTO Personal (DNI_Personal, Nombres_Personal, ApellidoPaterno_Personal, ApellidoMaterno_Personal, FechaNacimiento_Personal, Genero_Personal, ID_Condicion, ID_Profesion) "
                         + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection con = Conexion.getConexion();
             PreparedStatement pst = con.prepareStatement(sqlInsert)) {

            pst.setString(1, dni);
            pst.setString(2, nombres);
            pst.setString(3, apellidoP);
            pst.setString(4, apellidoM);
            pst.setDate(5, sqlDate);
            pst.setString(6, genero);
            pst.setInt(7, idCondicion);
            pst.setInt(8, idProfesion);

            int res = pst.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Registro agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo agregar el registro.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: " + e.getMessage());
        }
        cargarDatosTabla();
    }//GEN-LAST:event_bttAgregarActionPerformed

    private void jTablePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonalMouseClicked
        int filaSeleccionada = jTablePersonal.getSelectedRow();
        if (filaSeleccionada != -1) {
            String dni = jTablePersonal.getValueAt(filaSeleccionada, 0).toString();
            String nombres = jTablePersonal.getValueAt(filaSeleccionada, 1).toString();
            String apellidoP = jTablePersonal.getValueAt(filaSeleccionada, 2).toString();
            String apellidoM = jTablePersonal.getValueAt(filaSeleccionada, 3).toString();
            Object fechaObj = jTablePersonal.getValueAt(filaSeleccionada, 4);
            java.util.Date fechaNac = null;
            if (fechaObj instanceof java.util.Date) {
                fechaNac = (java.util.Date) fechaObj;
            } else {
                try {
                    fechaNac = new SimpleDateFormat("yyyy-MM-dd").parse(fechaObj.toString());
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }

            String genero = jTablePersonal.getValueAt(filaSeleccionada, 5).toString();
            String condicion = jTablePersonal.getValueAt(filaSeleccionada, 6).toString();
            String profesion = jTablePersonal.getValueAt(filaSeleccionada, 7).toString();
            txtDni.setText(dni);
            txtNombres.setText(nombres);
            txtApellidoP.setText(apellidoP);
            txtApellidoM.setText(apellidoM);
            jDateFechaNacimiento.setDate(fechaNac);
            jCombGenero.setSelectedItem(genero);
            jCombCondicion.setSelectedItem(condicion);
            jCombProfesion.setSelectedItem(profesion);
        }
    }//GEN-LAST:event_jTablePersonalMouseClicked

    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
        String dni = txtDni.getText();

        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro para eliminar");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este registro?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM Personal WHERE DNI_Personal=?";

            try (Connection con = Conexion.getConexion();
                 PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setString(1, dni);

                int res = ps.executeUpdate();

                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage());
            }
        }
        cargarDatosTabla();
    }//GEN-LAST:event_bttEliminarActionPerformed

    private void bttModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificarActionPerformed
        String dni = txtDni.getText();
        String nombres = txtNombres.getText();
        String apellidoP = txtApellidoP.getText();
        String apellidoM = txtApellidoM.getText();
        java.util.Date fechaNacimiento = jDateFechaNacimiento.getDate();
        String genero = jCombGenero.getSelectedItem().toString();
        String condicion = jCombCondicion.getSelectedItem().toString();
        String profesion = jCombProfesion.getSelectedItem().toString();
        if (dni.isEmpty() || nombres.isEmpty()) {
            JOptionPane.showMessageDialog(null, "DNI y Nombres son obligatorios");
            return;
        }
        int idCondicion = ConsultasSql.obtenerIdCondicion(condicion);
        int idProfesion = ConsultasSql.obtenerIdProfesion(profesion);
        java.sql.Date fechaSQL = new java.sql.Date(fechaNacimiento.getTime());

        String sql = "UPDATE Personal SET Nombres_Personal=?, ApellidoPaterno_Personal=?, ApellidoMaterno_Personal=?, FechaNacimiento_Personal=?, Genero_Personal=?, ID_Condicion=?, ID_Profesion=? WHERE DNI_Personal=?";

        try (Connection con = Conexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, nombres);
            ps.setString(2, apellidoP);
            ps.setString(3, apellidoM);
            ps.setDate(4, fechaSQL);
            ps.setString(5, genero);
            ps.setInt(6, idCondicion);
            ps.setInt(7, idProfesion);
            ps.setString(8, dni);

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Registro modificado con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar registro");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage());
        }
        cargarDatosTabla();
    }//GEN-LAST:event_bttModificarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        txtDni.setText("");
        txtNombres.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        jDateFechaNacimiento.setDate(null);
        jCombGenero.setSelectedIndex(-1);
        jCombCondicion.setSelectedIndex(-1);
        jCombProfesion.setSelectedIndex(-1);
    }//GEN-LAST:event_bttLimpiarActionPerformed

    
    
    public void cargarProfesiones(JComboBox<String> jCombProfesion) {
        String sql = "SELECT Desc_Profesion FROM Profesion";

        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            con = Conexion.getConexion();
            st = con.createStatement();
            rs = st.executeQuery(sql);

            jCombProfesion.removeAllItems();
            while (rs.next()) {
                jCombProfesion.addItem(rs.getString("Desc_Profesion"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar profesiones: " + e.getMessage());
        }
    }
    
    public void cargarTablaPersonal(JTable jTablePersonal) {
        String sql = "SELECT p.DNI_Personal, p.Nombres_Personal, p.ApellidoPaterno_Personal, " +
                     "p.ApellidoMaterno_Personal, p.FechaNacimiento_Personal, p.Genero_Personal, " +
                     "c.Desc_Condicion, pr.Desc_Profesion " +
                     "FROM Personal p " +
                     "INNER JOIN Condicion c ON p.ID_Condicion = c.ID_Condicion " +
                     "INNER JOIN Profesion pr ON p.ID_Profesion = pr.ID_Profesion " +
                     "ORDER BY p.Nombres_Personal";

        try (Connection con = Conexion.getConexion();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("DNI");
            model.addColumn("Nombres");
            model.addColumn("Apellido Paterno");
            model.addColumn("Apellido Materno");
            model.addColumn("Fecha Nacimiento");
            model.addColumn("Género");
            model.addColumn("Condición");
            model.addColumn("Profesión");

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getString("DNI_Personal");
                fila[1] = rs.getString("Nombres_Personal");
                fila[2] = rs.getString("ApellidoPaterno_Personal");
                fila[3] = rs.getString("ApellidoMaterno_Personal");
                fila[4] = rs.getDate("FechaNacimiento_Personal");
                fila[5] = rs.getString("Genero_Personal");
                fila[6] = rs.getString("Desc_Condicion");
                fila[7] = rs.getString("Desc_Profesion");

                model.addRow(fila);
            }

            jTablePersonal.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla personal: " + e.getMessage());
        }
    }

    
    public void cargarCondiciones(JComboBox<String> jCombCondicion) {
        String sql = "SELECT Desc_Condicion FROM Condicion";

        Connection con = null;
        Statement st = null;
        ResultSet rs = null;

        try {
            con = Conexion.getConexion();
            st = con.createStatement();
            rs = st.executeQuery(sql);

            jCombCondicion.removeAllItems();
            while (rs.next()) {
                jCombCondicion.addItem(rs.getString("Desc_Condicion"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar condiciones: " + e.getMessage());
        }
    }

    public void cargarDatosTabla() {
        String[] columnas = {"DNI", "Nombres", "Apellido Paterno", "Apellido Materno", "Fecha Nac.", "Género", "Condición", "Profesión"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        String sql = "SELECT p.DNI_Personal, p.Nombres_Personal, p.ApellidoPaterno_Personal, p.ApellidoMaterno_Personal, p.FechaNacimiento_Personal, p.Genero_Personal, c.Desc_Condicion, pr.Desc_Profesion " +
                     "FROM Personal p " +
                     "JOIN Condicion c ON p.ID_Condicion = c.ID_Condicion " +
                     "JOIN Profesion pr ON p.ID_Profesion = pr.ID_Profesion";

        try (Connection con = Conexion.getConexion();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getString("DNI_Personal");
                fila[1] = rs.getString("Nombres_Personal");
                fila[2] = rs.getString("ApellidoPaterno_Personal");
                fila[3] = rs.getString("ApellidoMaterno_Personal");
                fila[4] = rs.getDate("FechaNacimiento_Personal");
                fila[5] = rs.getString("Genero_Personal");
                fila[6] = rs.getString("Desc_Condicion");
                fila[7] = rs.getString("Desc_Profesion");
                modelo.addRow(fila);
            }

            jTablePersonal.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar datos en la tabla: " + e.getMessage());
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregar;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar;
    private javax.swing.JComboBox<String> jCombCondicion;
    private javax.swing.JComboBox<String> jCombGenero;
    private javax.swing.JComboBox<String> jCombProfesion;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonal;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
