/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.Gui;

import com.mycompany.Modelo.ValidarContrasena;
import com.mycompany.Modelo.Conexion;
import com.mycompany.Modelo.Encriptador;
import com.mycompany.Modelo.SesionUsuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author farro
 */
public class CambioContrasena extends javax.swing.JDialog {

    /**
     * Creates new form CambioContrasena
     */
    public CambioContrasena(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlabel8caracter = new javax.swing.JLabel();
        jlabel1mayuscula = new javax.swing.JLabel();
        jlabel1simbolo = new javax.swing.JLabel();
        jbttConfirmar = new javax.swing.JButton();
        bttCerrar = new javax.swing.JButton();
        jpassNuevaContrasena = new javax.swing.JPasswordField();
        jpassConfirmarContrasena = new javax.swing.JPasswordField();
        jbttMostrarContraseña2 = new javax.swing.JToggleButton();
        jbttMostrarContraseña1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Restablecer contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Ingrese su nueva contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Confirme su nueva contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lea atentamente los requisitos para poder actualizar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("su contraseña. Asegurese de que este bien escrito. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Requisistos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jlabel8caracter.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlabel8caracter.setForeground(new java.awt.Color(0, 0, 0));
        jlabel8caracter.setText("- Debe tener al menos 8 caracteres.");
        jPanel1.add(jlabel8caracter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jlabel1mayuscula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlabel1mayuscula.setForeground(new java.awt.Color(0, 0, 0));
        jlabel1mayuscula.setText("- Debe tener al menos 1 letra mayuscula.");
        jPanel1.add(jlabel1mayuscula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jlabel1simbolo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlabel1simbolo.setForeground(new java.awt.Color(0, 0, 0));
        jlabel1simbolo.setText("- Debe contener un símbolo *=#_%@.-/");
        jPanel1.add(jlabel1simbolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jbttConfirmar.setBackground(new java.awt.Color(0, 0, 102));
        jbttConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbttConfirmar.setText("Confirmar");
        jbttConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jbttConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, -1));

        bttCerrar.setBackground(new java.awt.Color(102, 0, 0));
        bttCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bttCerrar.setText("Cerrar");
        bttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(bttCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 320, 90, -1));
        jPanel1.add(jpassNuevaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 30));
        jPanel1.add(jpassConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 30));

        jbttMostrarContraseña2.setBackground(new java.awt.Color(255, 255, 255));
        jbttMostrarContraseña2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eye.png"))); // NOI18N
        jbttMostrarContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttMostrarContraseña2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbttMostrarContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, 30));

        jbttMostrarContraseña1.setBackground(new java.awt.Color(255, 255, 255));
        jbttMostrarContraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eye.png"))); // NOI18N
        jbttMostrarContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttMostrarContraseña1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbttMostrarContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttConfirmarActionPerformed
        String nuevaPass = new String(jpassNuevaContrasena.getPassword());
        String confirmarPass = new String(jpassConfirmarContrasena.getPassword());

        if (!nuevaPass.equals(confirmarPass)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!ValidarContrasena.tieneLongitudMinima(nuevaPass) ||
            !ValidarContrasena.tieneMayuscula(nuevaPass) ||
            !ValidarContrasena.tieneSimbolo(nuevaPass)) {
            JOptionPane.showMessageDialog(this, "La contraseña no cumple con los requisitos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String contrasenaCifrada = Encriptador.encriptarSHA256(nuevaPass);

        Connection con = null;
        PreparedStatement ps = null;

        try {
            con = Conexion.getConexion();
            String dniUsuario = SesionUsuario.getDniUsuario();

            String sql = "UPDATE Usuario SET Contraseña = ? WHERE DNI_Personal = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, contrasenaCifrada);
            ps.setString(2, dniUsuario);

            int filas = ps.executeUpdate();

            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente");
                limpiarCampos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar la contraseña");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_jbttConfirmarActionPerformed

    private void bttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_bttCerrarActionPerformed

    private void jbttMostrarContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttMostrarContraseña2ActionPerformed
        if (jpassConfirmarContrasena.getEchoChar() == (char) 0) {
            jpassConfirmarContrasena.setEchoChar('*');
        } else {
            jpassConfirmarContrasena.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_jbttMostrarContraseña2ActionPerformed

    private void jbttMostrarContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttMostrarContraseña1ActionPerformed
        if (jpassNuevaContrasena.getEchoChar() == (char) 0) {
            jpassNuevaContrasena.setEchoChar('*');
        } else {
            jpassNuevaContrasena.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_jbttMostrarContraseña1ActionPerformed

    public void limpiarCampos() {
        jpassNuevaContrasena.setText("");
        jpassConfirmarContrasena.setText("");
        jlabel8caracter.setForeground(java.awt.Color.RED);
        jlabel1mayuscula.setForeground(java.awt.Color.RED);
        jlabel1simbolo.setForeground(java.awt.Color.RED);
        jbttConfirmar.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CambioContrasena dialog = new CambioContrasena(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbttConfirmar;
    private javax.swing.JToggleButton jbttMostrarContraseña1;
    private javax.swing.JToggleButton jbttMostrarContraseña2;
    private javax.swing.JLabel jlabel1mayuscula;
    private javax.swing.JLabel jlabel1simbolo;
    private javax.swing.JLabel jlabel8caracter;
    private javax.swing.JPasswordField jpassConfirmarContrasena;
    private javax.swing.JPasswordField jpassNuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
