/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import com.mycompany.Modelo.Conexion;
import com.mycompany.Modelo.ConsultasSql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author farro
 */
public class Metas extends javax.swing.JFrame {

    /**
     * Creates new form Metas
     */
    public Metas() {
        initComponents();
        ConsultasSql.cargarAtenciones(cmbAtencion); 
        cmbRed.setEditable(true);
        cmbMicrored.setEditable(true);
        cmbEstablecimiento.setEditable(true);
        JTextField editor = (JTextField) cmbRed.getEditor().getEditorComponent();
        editor.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String texto = editor.getText();
                ConsultasSql.filtrarRedes(cmbRed, texto);
            }
        });  
        cargarMetasAsignadas(tableMostrarMetas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonalEstablecimiento = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMostrarMetas = new javax.swing.JTable();
        dateFechaFin = new com.toedter.calendar.JDateChooser();
        dateFechaInicio = new com.toedter.calendar.JDateChooser();
        txtNumeroMeta = new javax.swing.JTextField();
        cmbAtencion = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bttBuscarPersonal = new javax.swing.JButton();
        bttAsignarMeta = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        cmbEstablecimiento = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbRed = new javax.swing.JComboBox<>();
        txtDescProfesion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDescColegio = new javax.swing.JTextField();
        bttEditarMeta = new javax.swing.JButton();
        bttEliminarMeta = new javax.swing.JButton();
        cmbMicrored = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Control de Metas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Establecimiento:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 20));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 20));
        jPanel2.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Atencion:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 70, 20));

        tablePersonalEstablecimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePersonalEstablecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePersonalEstablecimientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePersonalEstablecimiento);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 640, 100));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Fecha Inicio:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Fecha Fin:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 70, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Numero de Meta:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, 20));

        tableMostrarMetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMostrarMetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMostrarMetasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMostrarMetas);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 640, 140));
        jPanel2.add(dateFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 130, -1));
        jPanel2.add(dateFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, -1));
        jPanel2.add(txtNumeroMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 60, -1));

        jPanel2.add(cmbAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 150, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Apellido P:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Colegio:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 60, 20));

        bttBuscarPersonal.setText("Buscar Personal");
        bttBuscarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarPersonalActionPerformed(evt);
            }
        });
        jPanel2.add(bttBuscarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        bttAsignarMeta.setText("Asignar Meta");
        bttAsignarMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAsignarMetaActionPerformed(evt);
            }
        });
        jPanel2.add(bttAsignarMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 120, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Asignar meta");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        cmbEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstablecimientoActionPerformed(evt);
            }
        });
        jPanel2.add(cmbEstablecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 350, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Red:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Microred:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 70, 20));

        cmbRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRedActionPerformed(evt);
            }
        });
        jPanel2.add(cmbRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 180, -1));
        jPanel2.add(txtDescProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Profesión:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 20));
        jPanel2.add(txtDescColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 130, -1));

        bttEditarMeta.setText("Editar Meta");
        bttEditarMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarMetaActionPerformed(evt);
            }
        });
        jPanel2.add(bttEditarMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 120, -1));

        bttEliminarMeta.setText("Eliminar Meta");
        bttEliminarMeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarMetaActionPerformed(evt);
            }
        });
        jPanel2.add(bttEliminarMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 120, -1));

        cmbMicrored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMicroredActionPerformed(evt);
            }
        });
        jPanel2.add(cmbMicrored, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, -1));

        jButton1.setText("Limpiar Campos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePersonalEstablecimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePersonalEstablecimientoMouseClicked
        int filaSeleccionada = tablePersonalEstablecimiento.getSelectedRow();
        if (filaSeleccionada != -1) {
            String nombres = tablePersonalEstablecimiento.getValueAt(filaSeleccionada, 0).toString();
            String apellidoPaterno = tablePersonalEstablecimiento.getValueAt(filaSeleccionada, 1).toString();
            String profesion = tablePersonalEstablecimiento.getValueAt(filaSeleccionada, 2).toString();
            String colegio = tablePersonalEstablecimiento.getValueAt(filaSeleccionada, 3).toString();
            txtNombre.setText(nombres);
            txtApellidoPaterno.setText(apellidoPaterno);
            txtDescProfesion.setText(profesion);
            txtDescColegio.setText(colegio);
        }
    }//GEN-LAST:event_tablePersonalEstablecimientoMouseClicked

    private void tableMostrarMetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMostrarMetasMouseClicked
        int filaSeleccionada = tableMostrarMetas.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Saltamos columna 0 (ID_MetaExamen)
            String meta = tableMostrarMetas.getValueAt(filaSeleccionada, 1).toString();
            java.util.Date fechaInicio = (java.util.Date) tableMostrarMetas.getValueAt(filaSeleccionada, 2);
            java.util.Date fechaFin = (java.util.Date) tableMostrarMetas.getValueAt(filaSeleccionada, 3);
            String nombre = tableMostrarMetas.getValueAt(filaSeleccionada, 4).toString();
            String apellidoPaterno = tableMostrarMetas.getValueAt(filaSeleccionada, 5).toString();
            String atencion = tableMostrarMetas.getValueAt(filaSeleccionada, 6).toString();
            Object establecimientoObj = tableMostrarMetas.getValueAt(filaSeleccionada, 7);
            String establecimiento = (establecimientoObj != null) ? establecimientoObj.toString() : "";

            txtNumeroMeta.setText(meta);
            dateFechaInicio.setDate(fechaInicio);
            dateFechaFin.setDate(fechaFin);
            txtNombre.setText(nombre);
            txtApellidoPaterno.setText(apellidoPaterno);
            cmbAtencion.setSelectedItem(atencion);
            cmbEstablecimiento.setSelectedItem(establecimiento);
        }
    }//GEN-LAST:event_tableMostrarMetasMouseClicked

    private void bttBuscarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarPersonalActionPerformed
        if (cmbRed.getSelectedItem() == null || cmbMicrored.getSelectedItem() == null || cmbEstablecimiento.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Red, Microred y Establecimiento.");
            return;
        }

        String establecimientoSeleccionado = cmbEstablecimiento.getSelectedItem().toString();
        ConsultasSql.buscarPersonalPorEstablecimiento(tablePersonalEstablecimiento, establecimientoSeleccionado);
    }//GEN-LAST:event_bttBuscarPersonalActionPerformed

    private void bttAsignarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAsignarMetaActionPerformed
        String cantidadStr = txtNumeroMeta.getText().trim();
        java.util.Date fechaInicio = dateFechaInicio.getDate();
        java.util.Date fechaFin = dateFechaFin.getDate();
        String atencionSeleccionada = cmbAtencion.getSelectedItem().toString();
        String establecimientoSeleccionado = cmbEstablecimiento.getSelectedItem().toString();
        String nombrePersonal = txtNombre.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();

        if (cantidadStr.isEmpty() || fechaInicio == null || fechaFin == null ||
            atencionSeleccionada == null || establecimientoSeleccionado == null ||
            nombrePersonal.isEmpty() || apellidoPaterno.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Complete todos los campos antes de asignar la meta.");
            return;
        }

        int cantidadMeta = Integer.parseInt(cantidadStr);
        int idAtencion = ConsultasSql.obtenerIdAtencion(atencionSeleccionada);
        int idEstablecimiento = ConsultasSql.obtenerIdEstablecimiento(establecimientoSeleccionado);
        String dni = ConsultasSql.obtenerDniPersonalPorNombre(nombrePersonal, apellidoPaterno);

        if (dni == null || idAtencion == -1 || idEstablecimiento == -1) {
            JOptionPane.showMessageDialog(null, "Error al obtener datos del personal, atención o establecimiento.");
            return;
        }

        java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
        java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());

        String sql = "INSERT INTO MetaExamen (Cantidad_MetaExamen, FechaInicio_MetaExamen, FechaFin_MetaExamen, DNI_Personal, ID_Atencion, ID_Establecimiento) "
        + "VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, cantidadMeta);
            ps.setDate(2, sqlFechaInicio);
            ps.setDate(3, sqlFechaFin);
            ps.setString(4, dni);
            ps.setInt(5, idAtencion);
            ps.setInt(6, idEstablecimiento);

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Meta asignada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo asignar la meta.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error SQL al asignar meta: " + e.getMessage());
        }
    }//GEN-LAST:event_bttAsignarMetaActionPerformed

    private void cmbEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstablecimientoActionPerformed

    }//GEN-LAST:event_cmbEstablecimientoActionPerformed

    private void cmbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRedActionPerformed
        if (cmbRed.getSelectedItem() != null) {
            String redSeleccionada = cmbRed.getSelectedItem().toString();
            ConsultasSql.cargarMicroredesPorRed(cmbMicrored, redSeleccionada);
        }
    }//GEN-LAST:event_cmbRedActionPerformed

    private void bttEditarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarMetaActionPerformed
        try {
            String nombre = txtNombre.getText().trim();
            String apellidoPaterno = txtApellidoPaterno.getText().trim();
            String dni = ConsultasSql.obtenerDniPersonalPorNombre(nombre, apellidoPaterno);
            if (dni == null) {
                JOptionPane.showMessageDialog(null, "No se pudo obtener el DNI del personal.");
                return;
            }

            int nuevaMeta = Integer.parseInt(txtNumeroMeta.getText().trim());
            String descAtencion = cmbAtencion.getSelectedItem().toString();
            int idAtencion = ConsultasSql.obtenerIdAtencion(descAtencion);
            if (idAtencion == -1) {
                JOptionPane.showMessageDialog(null, "Atención seleccionada no válida.");
                return;
            }

            java.sql.Date fechaInicio = new java.sql.Date(dateFechaInicio.getDate().getTime());
            java.sql.Date fechaFin = new java.sql.Date(dateFechaFin.getDate().getTime());

            String sql = "UPDATE MetaExamen SET Cantidad_MetaExamen = ?, ID_Atencion = ? " +
            "WHERE DNI_Personal = ? AND FechaInicio_MetaExamen = ? AND FechaFin_MetaExamen = ?";

            try (Connection con = Conexion.getConexion();
                PreparedStatement ps = con.prepareStatement(sql)) {

                ps.setInt(1, nuevaMeta);
                ps.setInt(2, idAtencion);
                ps.setString(3, dni);
                ps.setDate(4, fechaInicio);
                ps.setDate(5, fechaFin);

                int res = ps.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Meta actualizada correctamente.");
                    cargarMetasAsignadas(tableMostrarMetas);
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró una meta con los datos especificados.");
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al actualizar meta: " + e.getMessage());
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El número de meta debe ser un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_bttEditarMetaActionPerformed

    private void bttEliminarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarMetaActionPerformed
        int fila = tableMostrarMetas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una meta de la tabla.");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(null, "¿Deseas eliminar esta meta asignada?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirmar != JOptionPane.YES_OPTION) return;

        int idMeta = (int) tableMostrarMetas.getValueAt(fila, 0); // Columna 0 (aunque esté oculta)

        String sql = "DELETE FROM MetaExamen WHERE ID_MetaExamen = ?";

        try (Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, idMeta);
            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Meta eliminada correctamente.");
                cargarMetasAsignadas(tableMostrarMetas);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró la meta para eliminar.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error SQL al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_bttEliminarMetaActionPerformed

    private void cmbMicroredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMicroredActionPerformed
        if (cmbMicrored.getSelectedItem() != null) {
            String microredSeleccionada = cmbMicrored.getSelectedItem().toString();
            ConsultasSql.cargarEstablecimientosPorMicrored(cmbEstablecimiento, microredSeleccionada);
        }
    }//GEN-LAST:event_cmbMicroredActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void cargarMetasAsignadas(JTable tableMostrarMetas) {
        String[] columnas = {"ID", "Meta", "Fecha Inicio", "Fecha Fin", "Nombre", "Apellido Paterno", "Atención", "Establecimiento"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);

        String sql = "SELECT m.ID_MetaExamen, m.Cantidad_MetaExamen, m.FechaInicio_MetaExamen, m.FechaFin_MetaExamen, " +
                     "p.Nombres_Personal, p.ApellidoPaterno_Personal, a.Desc_Atencion, e.Nombre_Establecimiento " +
                     "FROM MetaExamen m " +
                     "INNER JOIN Personal p ON m.DNI_Personal = p.DNI_Personal " +
                     "INNER JOIN Atencion a ON m.ID_Atencion = a.ID_Atencion " +
                     "LEFT JOIN Establecimiento e ON m.ID_Establecimiento = e.ID_Establecimiento";

        try (Connection con = Conexion.getConexion();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getInt("ID_MetaExamen");
                fila[1] = rs.getInt("Cantidad_MetaExamen");
                fila[2] = rs.getDate("FechaInicio_MetaExamen");
                fila[3] = rs.getDate("FechaFin_MetaExamen");
                fila[4] = rs.getString("Nombres_Personal");
                fila[5] = rs.getString("ApellidoPaterno_Personal");
                fila[6] = rs.getString("Desc_Atencion");
                fila[7] = rs.getString("Nombre_Establecimiento");
                modelo.addRow(fila);
            }

            tableMostrarMetas.setModel(modelo);

            // Ocultar la primera columna (ID_MetaExamen)
            tableMostrarMetas.getColumnModel().getColumn(0).setMinWidth(0);
            tableMostrarMetas.getColumnModel().getColumn(0).setMaxWidth(0);
            tableMostrarMetas.getColumnModel().getColumn(0).setWidth(0);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar metas: " + e.getMessage());
        }
    }
   
    public void limpiarCampos(){
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtDescProfesion.setText("");
        txtDescColegio.setText("");
        dateFechaInicio.setDate(null);
        dateFechaFin.setDate(null);
        txtNumeroMeta.setText("");;
        cmbAtencion.setSelectedItem(-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAsignarMeta;
    private javax.swing.JButton bttBuscarPersonal;
    private javax.swing.JButton bttEditarMeta;
    private javax.swing.JButton bttEliminarMeta;
    private javax.swing.JComboBox<String> cmbAtencion;
    private javax.swing.JComboBox<String> cmbEstablecimiento;
    private javax.swing.JComboBox<String> cmbMicrored;
    private javax.swing.JComboBox<String> cmbRed;
    private com.toedter.calendar.JDateChooser dateFechaFin;
    private com.toedter.calendar.JDateChooser dateFechaInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMostrarMetas;
    private javax.swing.JTable tablePersonalEstablecimiento;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtDescColegio;
    private javax.swing.JTextField txtDescProfesion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroMeta;
    // End of variables declaration//GEN-END:variables
}
