/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Gui;

import com.mycompany.Modelo.SesionUsuario;
import javax.swing.JOptionPane;
/**
 *
 * @author farro
 */
public class Principal extends javax.swing.JFrame {

    private boolean puedeAccederCita = false;
    private boolean puedeAccederPersonal = false;
    private boolean puedeAccederAtencion = false;
    private boolean puedeAccederReporte = false;
    private boolean puedeAccederMetas = false;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bttCita = new javax.swing.JButton();
        bttPersonal = new javax.swing.JButton();
        bttReporte = new javax.swing.JButton();
        bttLogin = new javax.swing.JButton();
        bttCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bttAtencion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        bttMetas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Centro de Salud");

        bttCita.setBackground(new java.awt.Color(255, 255, 255));
        bttCita.setForeground(new java.awt.Color(0, 0, 0));
        bttCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Calendar.png"))); // NOI18N
        bttCita.setText("    Cita");
        bttCita.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCitaActionPerformed(evt);
            }
        });

        bttPersonal.setBackground(new java.awt.Color(255, 255, 255));
        bttPersonal.setForeground(new java.awt.Color(0, 0, 0));
        bttPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Personal.png"))); // NOI18N
        bttPersonal.setText("    Personal");
        bttPersonal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPersonalActionPerformed(evt);
            }
        });

        bttReporte.setBackground(new java.awt.Color(255, 255, 255));
        bttReporte.setForeground(new java.awt.Color(0, 0, 0));
        bttReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/statistics.png"))); // NOI18N
        bttReporte.setText("    Reporte");
        bttReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });

        bttLogin.setBackground(new java.awt.Color(255, 255, 255));
        bttLogin.setForeground(new java.awt.Color(0, 0, 0));
        bttLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Person.png"))); // NOI18N
        bttLogin.setText("    Login");
        bttLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });

        bttCerrar.setBackground(new java.awt.Color(204, 204, 204));
        bttCerrar.setForeground(new java.awt.Color(0, 0, 0));
        bttCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Close.png"))); // NOI18N
        bttCerrar.setText("    Cerrar");
        bttCerrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salud.png"))); // NOI18N

        bttAtencion.setBackground(new java.awt.Color(255, 255, 255));
        bttAtencion.setForeground(new java.awt.Color(0, 0, 0));
        bttAtencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Report.png"))); // NOI18N
        bttAtencion.setText("    Atencion");
        bttAtencion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAtencionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        bttMetas.setBackground(new java.awt.Color(255, 255, 255));
        bttMetas.setForeground(new java.awt.Color(0, 0, 0));
        bttMetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meta.png"))); // NOI18N
        bttMetas.setText("    Metas");
        bttMetas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bttMetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6))
                    .addComponent(bttMetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttCita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttAtencion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttMetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(bttLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttCerrar)
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 560));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo principal.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 660, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCitaActionPerformed
        if (!puedeAccederCita) {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
            return;
        }
        Cita cita = new Cita();
        cita.setVisible(true);
        cita.setLocation(428, 72);
    }//GEN-LAST:event_bttCitaActionPerformed

    private void bttPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPersonalActionPerformed
        if (!puedeAccederPersonal) {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
            return;
        }
        GestionarPersonal personal = new GestionarPersonal();
        personal.setVisible(true);
        personal.setLocation(428, 72);
    }//GEN-LAST:event_bttPersonalActionPerformed

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        if (!puedeAccederReporte) {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
            return;
        }
        Reportes reportes = new Reportes();
        reportes.setVisible(true);
        reportes.setLocation(428,72);
    }//GEN-LAST:event_bttReporteActionPerformed
 
    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        Sesion sesion = new Sesion(this, true);
        sesion.setVisible(true);

        if (SesionUsuario.getCorreoUsuario() != null) {
            System.out.println("Sesión activa, cargando datos en Principal...");
            labelUsuario.setText(SesionUsuario.getCorreoUsuario());

            String rol = SesionUsuario.getCargoUsuario();
            System.out.println("rol obtenido: " + rol);

            puedeAccederCita = false;
            puedeAccederPersonal = false;
            puedeAccederAtencion = false;
            puedeAccederReporte = false;
            puedeAccederMetas = false;

            switch (rol) {
                case "Jefe de Area":
                puedeAccederCita = true;
                puedeAccederPersonal = true;
                puedeAccederAtencion = true;
                puedeAccederReporte = true;
                puedeAccederMetas = true;
                break;
                case "Usuario Limitado":
                puedeAccederCita = true;
                puedeAccederAtencion = true;
                break;
                case "Admin":
                puedeAccederPersonal = true;
                break;
                default:
                JOptionPane.showMessageDialog(this, "Rol no reconocido: " + rol);
            }

            // Activar o desactivar botones según permisos
            bttCita.setEnabled(puedeAccederCita);
            bttPersonal.setEnabled(puedeAccederPersonal);
            bttAtencion.setEnabled(puedeAccederAtencion);
            bttReporte.setEnabled(puedeAccederReporte);
            bttMetas.setEnabled(puedeAccederMetas);

        } else {
            System.out.println("Sesión no activa. No se cargó usuario.");
        }
    }//GEN-LAST:event_bttLoginActionPerformed

    private void bttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Deseas cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {

            // Limpiar datos de sesión
            SesionUsuario.clear();

            // Limpiar interfaz
            labelUsuario.setText("Sin usuario");

            // Desactivar permisos
            puedeAccederCita = false;
            puedeAccederPersonal = false;
            puedeAccederAtencion = false;
            puedeAccederReporte = false;
            puedeAccederMetas = false;

            // Desactivar botones
            bttCita.setEnabled(false);
            bttPersonal.setEnabled(false);
            bttAtencion.setEnabled(false);
            bttReporte.setEnabled(false);
            bttMetas.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Sesión cerrada exitosamente.");
        }
    }//GEN-LAST:event_bttCerrarActionPerformed

    private void bttAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAtencionActionPerformed
        if (!puedeAccederAtencion) {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
            return;
        }
        Atencion atencion = new Atencion();
        atencion.setVisible(true);
        atencion.setLocation(428,72);
    }//GEN-LAST:event_bttAtencionActionPerformed

    private void bttMetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMetasActionPerformed
        if (!puedeAccederMetas) {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
            return;
        }
        Metas metas = new Metas();
        metas.setVisible(true);
        metas.setLocation(428,72);
    }//GEN-LAST:event_bttMetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAtencion;
    private javax.swing.JButton bttCerrar;
    private javax.swing.JButton bttCita;
    private javax.swing.JButton bttLogin;
    private javax.swing.JButton bttMetas;
    private javax.swing.JButton bttPersonal;
    private javax.swing.JButton bttReporte;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
