/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.Gui;

import com.mycompany.Modelo.GenerarCaptcha;
import com.mycompany.Modelo.Conexion;
import com.mycompany.Modelo.Encriptador;
import com.mycompany.Modelo.SesionUsuario;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author farro
 */
public class Sesion extends javax.swing.JDialog {

    /**
     * Creates new form Sesion
     */
    public Sesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 100));  // Fondo transparente (ARGB)
        initComponents();
        jtxtGenerarCaptcha.setText(GenerarCaptcha.generarCodigo());
        setLocation(580, 102);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbttConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtGenerarCaptcha = new javax.swing.JTextField();
        jtxtEscribirCaptcha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bttGenerarCaptcha = new javax.swing.JToggleButton();
        jbttMostrarContraseña = new javax.swing.JToggleButton();
        jpassContrasena = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        bttRestaurarContraseña = new javax.swing.JToggleButton();
        jbttCerrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(164, 216, 224));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbttConfirmar.setBackground(new java.awt.Color(0, 0, 102));
        jbttConfirmar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbttConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbttConfirmar.setText("Confirmar");
        jbttConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(jbttConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Correo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jtxtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jtxtCorreo.setForeground(new java.awt.Color(0, 0, 51));
        jPanel1.add(jtxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Person.png"))); // NOI18N
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 20, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Captcha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Security20px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, 30));

        jtxtGenerarCaptcha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jtxtGenerarCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 110, 30));

        jtxtEscribirCaptcha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jtxtEscribirCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo_hospital.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 90));

        bttGenerarCaptcha.setBackground(new java.awt.Color(255, 255, 255));
        bttGenerarCaptcha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Restore.png"))); // NOI18N
        bttGenerarCaptcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGenerarCaptchaActionPerformed(evt);
            }
        });
        jPanel1.add(bttGenerarCaptcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 30, 30));

        jbttMostrarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        jbttMostrarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eye.png"))); // NOI18N
        jbttMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttMostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jbttMostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 30, 30));

        jpassContrasena.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jpassContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 30));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 40, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, 30));

        bttRestaurarContraseña.setBackground(new java.awt.Color(164, 217, 224));
        bttRestaurarContraseña.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bttRestaurarContraseña.setForeground(new java.awt.Color(0, 0, 51));
        bttRestaurarContraseña.setText("¿Olvidaste tu contraseña?");
        bttRestaurarContraseña.setBorder(null);
        bttRestaurarContraseña.setContentAreaFilled(false);
        bttRestaurarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRestaurarContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(bttRestaurarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 180, -1));

        jbttCerrar.setBackground(new java.awt.Color(153, 0, 0));
        jbttCerrar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbttCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbttCerrar.setText("Cerrar");
        jbttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbttCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttConfirmarActionPerformed
        String correo = jtxtCorreo.getText().trim();
        String contrasena = new String(jpassContrasena.getPassword());
        String captchaGenerado = jtxtGenerarCaptcha.getText().trim();
        String captchaIngresado = jtxtEscribirCaptcha.getText().trim();

        if (correo.isEmpty() || contrasena.isEmpty() || captchaIngresado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        if (!captchaGenerado.equals(captchaIngresado)) {
            JOptionPane.showMessageDialog(this, "Captcha incorrecto.");
            jtxtGenerarCaptcha.setText(GenerarCaptcha.generarCodigo());
            return;
        }

        String contrasenaEncriptada = Encriptador.encriptarSHA256(contrasena);

        try (Connection con = Conexion.getConexion()) {
            String sql = "SELECT DNI_Personal, Correo, Rol FROM Usuario WHERE Correo = ? AND Contraseña = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, correo);
            ps.setString(2, contrasenaEncriptada);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String dni = rs.getString("DNI_Personal");
                String correoObtenido = rs.getString("Correo");
                String rol = rs.getString("Rol");

                SesionUsuario.setUsuario(dni, correoObtenido, rol);
                System.out.println("DNI_Personal: " + SesionUsuario.getDniUsuario());
                System.out.println("Correo: " + SesionUsuario.getCorreoUsuario());
                System.out.println("Rol: " + SesionUsuario.getCargoUsuario());

                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la conexión: " + e.getMessage());
        }
    }//GEN-LAST:event_jbttConfirmarActionPerformed

    private void bttGenerarCaptchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGenerarCaptchaActionPerformed
        jtxtGenerarCaptcha.setText(GenerarCaptcha.generarCodigo());
    }//GEN-LAST:event_bttGenerarCaptchaActionPerformed

    private void jbttMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttMostrarContraseñaActionPerformed
        if (jpassContrasena.getEchoChar() == (char) 0) {
            jpassContrasena.setEchoChar('*');
        } else {
            jpassContrasena.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_jbttMostrarContraseñaActionPerformed

    private void bttRestaurarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRestaurarContraseñaActionPerformed
        RecuperarContrasena recuperarcontrasena = new RecuperarContrasena(this, true);
        recuperarcontrasena.setLocation(580, 102);
        recuperarcontrasena.setVisible(true);
    }//GEN-LAST:event_bttRestaurarContraseñaActionPerformed

    private void jbttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jbttCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Sesion dialog = new Sesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bttGenerarCaptcha;
    private javax.swing.JToggleButton bttRestaurarContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jbttCerrar;
    private javax.swing.JButton jbttConfirmar;
    private javax.swing.JToggleButton jbttMostrarContraseña;
    private javax.swing.JPasswordField jpassContrasena;
    private javax.swing.JTextField jtxtCorreo;
    private javax.swing.JTextField jtxtEscribirCaptcha;
    private javax.swing.JTextField jtxtGenerarCaptcha;
    // End of variables declaration//GEN-END:variables
}
